# Generated by Django 2.0.4 on 2018-05-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayGroupsSubject',
            fields=[
                ('id_day_groups_subject', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'day_groups_subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DayOfTheWeek',
            fields=[
                ('day_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'day_of_the_week',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_cipher', models.IntegerField(unique=True)),
                ('students_count', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('cource', models.IntegerField()),
            ],
            options={
                'db_table': 'groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonNumbers',
            fields=[
                ('lesson_number', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_begin', models.TimeField()),
                ('lesson_end', models.TimeField()),
            ],
            options={
                'db_table': 'lesson_numbers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParityOdd',
            fields=[
                ('id_number', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'parity_odd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_cipher', models.IntegerField(unique=True)),
                ('lesson_type', models.CharField(max_length=10)),
                ('lecture_hall', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('academic_degree', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('election_date', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
    ]
